import{a as m,S as p,i as l}from"./assets/vendor-DnBR8w-b.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();function f(t){const r={key:"49512194-f753c2f34a7e7dbbd609db53f",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0};return m.get("https://pixabay.com/api/",{params:r})}function y(t,r){const n=r.map(o=>`<li class="gallery-item">
    <a class="image-link" href="${o.largeImageURL}"><img class="image" src="${o.webformatURL}" alt="${o.tags}" title=""/></a>
    <ul class="image-descr-list">
<li class="descr-item">Likes<span class="descr-span">${o.likes}</span></li>
<li class="descr-item">Views<span class="descr-span">${o.views}</span></li>
<li class="descr-item">Comments<span class="descr-span">${o.comments}</span></li>
<li class="descr-item">Downloads<span class="descr-span">${o.downloads}</span></li>
    </ul>
    </li>`).join("");t.insertAdjacentHTML("beforeend",n),h()}const g=new p(".gallery-item a",{captionsData:"alt",captionDelay:250});function h(){g.refresh()}function L(t){t.innerHTML=""}function b(){const t=document.querySelector(".loader");t.style.display="flex"}function u(){const t=document.querySelector(".loader");t.style.display="none"}const d=document.querySelector(".gallery"),c=document.querySelector(".form"),a=c.elements[0];a.classList.add("input");const w=c.elements[1];w.classList.add("button");c.addEventListener("submit",S);function S(t){if(t.preventDefault(),L(d),b(),a.value===""){u(),l.error({message:"Write your something you want to see",position:"topRight"});return}f(a.value).then(r=>{if(r.data.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(d,r.data.hits)}).catch(()=>{l.error({message:"Bad request",position:"topRight"})}).finally(()=>{u(),a.value=""})}
//# sourceMappingURL=index.js.map
